// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9u3GxjhgwXkxtS-rR3L4B6VuqDBMt_EE',
    appId: '1:262470075082:web:188395e974b6218b4fea33',
    messagingSenderId: '262470075082',
    projectId: 'flutter-notes-app-24be2',
    authDomain: 'flutter-notes-app-24be2.firebaseapp.com',
    storageBucket: 'flutter-notes-app-24be2.firebasestorage.app',
    measurementId: 'G-PRHDTWPBJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRIyvL26ZmS4WeV0vB4QZKMwMbHDE-cM',
    appId: '1:262470075082:android:6705b4ee0f858afa4fea33',
    messagingSenderId: '262470075082',
    projectId: 'flutter-notes-app-24be2',
    storageBucket: 'flutter-notes-app-24be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcITwRLDQAAn5hv_gzbBDzQ6CTWMGIu30',
    appId: '1:262470075082:ios:285e333a437295124fea33',
    messagingSenderId: '262470075082',
    projectId: 'flutter-notes-app-24be2',
    storageBucket: 'flutter-notes-app-24be2.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcITwRLDQAAn5hv_gzbBDzQ6CTWMGIu30',
    appId: '1:262470075082:ios:285e333a437295124fea33',
    messagingSenderId: '262470075082',
    projectId: 'flutter-notes-app-24be2',
    storageBucket: 'flutter-notes-app-24be2.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9u3GxjhgwXkxtS-rR3L4B6VuqDBMt_EE',
    appId: '1:262470075082:web:922d3efaec61378a4fea33',
    messagingSenderId: '262470075082',
    projectId: 'flutter-notes-app-24be2',
    authDomain: 'flutter-notes-app-24be2.firebaseapp.com',
    storageBucket: 'flutter-notes-app-24be2.firebasestorage.app',
    measurementId: 'G-7LT461S19D',
  );

}